"""Map team names from external sources to FIFA codes."""

TEAM_NAME_TO_FIFA: dict[str, str] = {
    "mexico": "MEX",
    "south africa": "RSA",
    "south korea": "KOR",
    "korea republic": "KOR",
    "czech republic": "CZE",
    "czechia": "CZE",
    "canada": "CAN",
    "bosnia & herzegovina": "BIH",
    "bosnia and herzegovina": "BIH",
    "bosnia-herzegovina": "BIH",
    "qatar": "QAT",
    "switzerland": "SUI",
    "brazil": "BRA",
    "morocco": "MAR",
    "haiti": "HAI",
    "scotland": "SCO",
    "usa": "USA",
    "united states": "USA",
    "paraguay": "PAR",
    "australia": "AUS",
    "turkey": "TUR",
    "türkiye": "TUR",
    "turkiye": "TUR",
    "germany": "GER",
    "curaçao": "CUW",
    "curacao": "CUW",
    "ivory coast": "CIV",
    "cote d'ivoire": "CIV",
    "côte d'ivoire": "CIV",
    "ecuador": "ECU",
    "netherlands": "NED",
    "japan": "JPN",
    "sweden": "SWE",
    "tunisia": "TUN",
    "belgium": "BEL",
    "egypt": "EGY",
    "iran": "IRN",
    "ir iran": "IRN",
    "new zealand": "NZL",
    "spain": "ESP",
    "cape verde": "CPV",
    "cabo verde": "CPV",
    "saudi arabia": "KSA",
    "uruguay": "URU",
    "france": "FRA",
    "senegal": "SEN",
    "iraq": "IRQ",
    "norway": "NOR",
    "argentina": "ARG",
    "algeria": "ALG",
    "austria": "AUT",
    "jordan": "JOR",
    "portugal": "POR",
    "dr congo": "COD",
    "congo dr": "COD",
    "democratic republic of the congo": "COD",
    "uzbekistan": "UZB",
    "colombia": "COL",
    "england": "ENG",
    "croatia": "CRO",
    "ghana": "GHA",
    "panama": "PAN",
}

WIKIDATA_TEAM_LABELS: dict[str, str] = {
    "Mexico national football team": "MEX",
    "South Africa national soccer team": "RSA",
    "South Korea national football team": "KOR",
    "Czech Republic national football team": "CZE",
    "Canada men's national soccer team": "CAN",
    "Bosnia and Herzegovina national football team": "BIH",
    "Qatar national football team": "QAT",
    "Switzerland men's national football team": "SUI",
    "Brazil national football team": "BRA",
    "Morocco national football team": "MAR",
    "Haiti national football team": "HAI",
    "Scotland national football team": "SCO",
    "United States men's national soccer team": "USA",
    "Paraguay national football team": "PAR",
    "Australia men's national soccer team": "AUS",
    "Turkey national football team": "TUR",
    "Germany national football team": "GER",
    "Curaçao national football team": "CUW",
    "Ivory Coast national football team": "CIV",
    "Ecuador national football team": "ECU",
    "Netherlands national football team": "NED",
    "Japan national football team": "JPN",
    "Sweden men's national football team": "SWE",
    "Tunisia national football team": "TUN",
    "Belgium national football team": "BEL",
    "Egypt national football team": "EGY",
    "Iran national football team": "IRN",
    "New Zealand men's national football team": "NZL",
    "Spain national football team": "ESP",
    "Cape Verde national football team": "CPV",
    "Saudi Arabia national football team": "KSA",
    "Uruguay national football team": "URU",
    "France national football team": "FRA",
    "Senegal national football team": "SEN",
    "Iraq national football team": "IRQ",
    "Norway national football team": "NOR",
    "Argentina national football team": "ARG",
    "Algeria national football team": "ALG",
    "Austria national football team": "AUT",
    "Jordan national football team": "JOR",
    "Portugal national football team": "POR",
    "DR Congo national football team": "COD",
    "Uzbekistan national football team": "UZB",
    "Colombia national football team": "COL",
    "England national football team": "ENG",
    "Croatia national football team": "CRO",
    "Ghana national football team": "GHA",
    "Panama national football team": "PAN",
}


def name_to_fifa(name: str) -> str | None:
    if not name:
        return None
    key = name.strip().lower()
    if key in TEAM_NAME_TO_FIFA:
        return TEAM_NAME_TO_FIFA[key]
    for label, code in WIKIDATA_TEAM_LABELS.items():
        if label.lower() == key or name.lower() in label.lower():
            return code
    return TEAM_NAME_TO_FIFA.get(key.replace(" national football team", "").replace(" national soccer team", ""))
