import { normalizeHistoryTeamName } from "./historyTeamNames";

export const HISTORY_CONTINENTS = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "Oceania",
  "South America",
] as const;

export type HistoryContinent = (typeof HISTORY_CONTINENTS)[number];

const TEAM_CONTINENT: Record<string, HistoryContinent> = {
  Algeria: "Africa",
  Angola: "Africa",
  Cameroon: "Africa",
  "Côte d'Ivoire": "Africa",
  Egypt: "Africa",
  Ghana: "Africa",
  Morocco: "Africa",
  Nigeria: "Africa",
  Senegal: "Africa",
  "South Africa": "Africa",
  Togo: "Africa",
  Tunisia: "Africa",
  Zaire: "Africa",
  "DR Congo": "Africa",
  China: "Asia",
  Iran: "Asia",
  Iraq: "Asia",
  Israel: "Asia",
  Japan: "Asia",
  Jordan: "Asia",
  Kuwait: "Asia",
  "North Korea": "Asia",
  Qatar: "Asia",
  "Saudi Arabia": "Asia",
  "South Korea": "Asia",
  "United Arab Emirates": "Asia",
  Uzbekistan: "Asia",
  Austria: "Europe",
  Belgium: "Europe",
  "Bosnia and Herzegovina": "Europe",
  Bulgaria: "Europe",
  Croatia: "Europe",
  "Czech Republic": "Europe",
  Czechoslovakia: "Europe",
  Denmark: "Europe",
  England: "Europe",
  France: "Europe",
  Germany: "Europe",
  "East Germany": "Europe",
  "West Germany": "Europe",
  "FR Germany": "Europe",
  "Dutch East Indies": "Asia",
  Greece: "Europe",
  Hungary: "Europe",
  Iceland: "Europe",
  Ireland: "Europe",
  Italy: "Europe",
  Netherlands: "Europe",
  "Northern Ireland": "Europe",
  Norway: "Europe",
  Poland: "Europe",
  Portugal: "Europe",
  Romania: "Europe",
  Russia: "Europe",
  Scotland: "Europe",
  Serbia: "Europe",
  "Serbia and Montenegro": "Europe",
  Slovakia: "Europe",
  Slovenia: "Europe",
  "Soviet Union": "Europe",
  Spain: "Europe",
  Sweden: "Europe",
  Switzerland: "Europe",
  Turkey: "Europe",
  Ukraine: "Europe",
  Wales: "Europe",
  Yugoslavia: "Europe",
  Canada: "North America",
  "Costa Rica": "North America",
  Cuba: "North America",
  "Curaçao": "North America",
  "El Salvador": "North America",
  Haiti: "North America",
  Honduras: "North America",
  Jamaica: "North America",
  Mexico: "North America",
  Panama: "North America",
  "Trinidad and Tobago": "North America",
  "United States": "North America",
  Australia: "Oceania",
  "New Zealand": "Oceania",
  Argentina: "South America",
  Bolivia: "South America",
  Brazil: "South America",
  Chile: "South America",
  Colombia: "South America",
  Ecuador: "South America",
  Paraguay: "South America",
  Peru: "South America",
  Uruguay: "South America",
};

export function getHistoryTeamContinent(teamName: string): HistoryContinent | null {
  const normalized = normalizeHistoryTeamName(teamName);
  return TEAM_CONTINENT[normalized] ?? null;
}
