const FIFA_TO_FLAG: Record<string, string> = {
  ALG: "dz",
  ARG: "ar",
  AUS: "au",
  AUT: "at",
  BEL: "be",
  BIH: "ba",
  BRA: "br",
  CAN: "ca",
  CHI: "cl",
  COL: "co",
  CPV: "cv",
  CRC: "cr",
  CRO: "hr",
  CZE: "cz",
  CIV: "ci",
  COD: "cd",
  CUW: "cw",
  DEN: "dk",
  ECU: "ec",
  EGY: "eg",
  ENG: "gb-eng",
  ESP: "es",
  FRA: "fr",
  GER: "de",
  GHA: "gh",
  GRE: "gr",
  HAI: "ht",
  HON: "hn",
  IRQ: "iq",
  IRN: "ir",
  ISL: "is",
  ITA: "it",
  JOR: "jo",
  JPN: "jp",
  KOR: "kr",
  KSA: "sa",
  MAR: "ma",
  MEX: "mx",
  NED: "nl",
  NGA: "ng",
  NOR: "no",
  NZL: "nz",
  PAN: "pa",
  PAR: "py",
  PER: "pe",
  POL: "pl",
  POR: "pt",
  QAT: "qa",
  RSA: "za",
  RUS: "ru",
  SCO: "gb-sct",
  SEN: "sn",
  SRB: "rs",
  SUI: "ch",
  SVK: "sk",
  SVN: "si",
  SWE: "se",
  TUN: "tn",
  TUR: "tr",
  URU: "uy",
  USA: "us",
  UZB: "uz",
  WAL: "gb-wls",
  CMR: "cm",
  CHN: "cn",
  CUB: "cu",
  ELS: "sv",
  GBR: "gb",
  IRL: "ie",
  NIR: "gb-nir",
  UKR: "ua",
};

const NAME_TO_FLAG: Record<string, string> = {
  algeria: "dz",
  argentina: "ar",
  australia: "au",
  austria: "at",
  belgium: "be",
  "bosnia and herzegovina": "ba",
  "bosnia & herzegovina": "ba",
  brazil: "br",
  cameroon: "cm",
  canada: "ca",
  chile: "cl",
  china: "cn",
  colombia: "co",
  "costa rica": "cr",
  croatia: "hr",
  "czech republic": "cz",
  czechia: "cz",
  "cote d'ivoire": "ci",
  "côte d'ivoire": "ci",
  "ivory coast": "ci",
  "cabo verde": "cv",
  "cape verde": "cv",
  curacao: "cw",
  "curaçao": "cw",
  denmark: "dk",
  ecuador: "ec",
  egypt: "eg",
  england: "gb-eng",
  france: "fr",
  germany: "de",
  "west germany": "de",
  "fr germany": "de",
  "east germany": "de",
  czechoslovakia: "cz",
  "soviet union": "ru",
  "dutch east indies": "id",
  ghana: "gh",
  greece: "gr",
  haiti: "ht",
  honduras: "hn",
  iran: "ir",
  "ir iran": "ir",
  iraq: "iq",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  jordan: "jo",
  "korea republic": "kr",
  "south korea": "kr",
  mexico: "mx",
  morocco: "ma",
  netherlands: "nl",
  "new zealand": "nz",
  nigeria: "ng",
  "north korea": "kp",
  norway: "no",
  panama: "pa",
  paraguay: "py",
  peru: "pe",
  poland: "pl",
  portugal: "pt",
  qatar: "qa",
  romania: "ro",
  russia: "ru",
  "saudi arabia": "sa",
  scotland: "gb-sct",
  senegal: "sn",
  serbia: "rs",
  slovakia: "sk",
  slovenia: "si",
  "south africa": "za",
  spain: "es",
  sweden: "se",
  switzerland: "ch",
  togo: "tg",
  trinidad: "tt",
  "trinidad and tobago": "tt",
  tunisia: "tn",
  turkey: "tr",
  turkiye: "tr",
  "türkiye": "tr",
  ukraine: "ua",
  uruguay: "uy",
  usa: "us",
  "united states": "us",
  uzbekistan: "uz",
  wales: "gb-wls",
  yugoslavia: "rs",
  zaire: "cd",
  "dr congo": "cd",
  "congo dr": "cd",
  "democratic republic of the congo": "cd",
};

function normalizeTeamName(name: string) {
  return name.trim().toLowerCase();
}

export function getFlagCode(fifaCode?: string | null, teamName?: string | null): string | null {
  if (fifaCode) {
    return FIFA_TO_FLAG[fifaCode.toUpperCase()] ?? null;
  }

  if (teamName) {
    return NAME_TO_FLAG[normalizeTeamName(teamName)] ?? null;
  }

  return null;
}

export function getTeamFlagUrl(fifaCode?: string | null, teamName?: string | null): string | null {
  const code = getFlagCode(fifaCode, teamName);
  return code ? `https://flagcdn.com/w320/${code}.png` : null;
}
